source ~/.vim/vimrc.d/disable-plugins.vim
source ~/.vim/vimrc.d/enable-plugins.vim
source ~/.vim/vimrc.d/configure-plugins.vim
source ~/.vim/vimrc.d/neovim-defaults-for-vim.vim
source ~/.vim/vimrc.d/options.vim
source ~/.vim/vimrc.d/commands.vim
source ~/.vim/vimrc.d/mappings/normal-visual-operator.vim
source ~/.vim/vimrc.d/mappings/insert-command-line.vim
source ~/.vim/vimrc.d/mappings/terminal.vim
source ~/.vim/vimrc.d/finalize.vim
