source <sfile>:h/vimrc.d/disable-plugins.vim
source <sfile>:h/vimrc.d/enable-plugins.vim
source <sfile>:h/vimrc.d/configure-plugins.vim
source <sfile>:h/vimrc.d/neovim-defaults-for-vim.vim
source <sfile>:h/vimrc.d/options.vim
source <sfile>:h/vimrc.d/autocmd.vim
source <sfile>:h/vimrc.d/commands.vim
source <sfile>:h/vimrc.d/mappings/normal-visual-operator.vim
source <sfile>:h/vimrc.d/mappings/insert-command-line.vim
source <sfile>:h/vimrc.d/mappings/terminal.vim
source <sfile>:h/vimrc.d/set-colorscheme.vim
